version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "yourStrongPassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sqlserver_data:/var/opt/mssql

  sportstore:
    build: .
    ports:
      - "8080:80"
    environment:
      DOTNET_ConnectionStrings__SqlDatabase: "Server=sqlserver;Database=SportStoreDB;User Id=sa;Password=yourStrongPassword;"
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
